### ISSUE TITLE
"Paste mark from clipboard" not available on Windows 8

### ISSUE THREAD

**Issue by Erickalon** [antipole2/PointUtility#3]
In the context menu on W8 computer the "Paste mark from clipboard" function doesn4t appear. Maybe not activated on this trial version?

**Comment by Erickalon** [comment]
Yes, I have copied a mark previously but the only choice is "past mark" and the mark is pasted in the position of the pointer.

**Comment by antipole2** [comment]
Very strange.
Please stop the script and make these temporary changes:

1.  Line 5 change to `trace = true;`  This will print stuff for me.
2. One possible issue is that we might have hit some limit on how many context menu items are accepted.  Comment out line 28 so it reads
`	// OCPNonContextMenu(pasteMark, "Paste mark");`
This will remove the Paste mark item.  Does `Paste mark from clipboard` then show?
3. Perhaps `Paste mark from clipboard` is too long a name?  Change the name in line 30 to "Clipboard".  Does that work?

You can reload the original script using Load and then select from recents

**Comment by Erickalon** [comment]
Sorry for the delay, I was working in the garden during a rather short sunny period!
The line's numbers are not as per your instructions, I have found 
"trace = false;" on line 4,
"OCPNonContextMenu(pasteMark, "Paste mark");" on line 25, 
but included in the following sentence: if (_remember.pointUtilitySet) OCPNonContextMenu(pasteMark, "Paste mark");
and isolated on lines 43 and 49.
But I have commented out the line 25: the choice "paste mark" disappears from context menu but I don't get "paste from clipboard". 
I have not found the string "Paste mark from clipboard" in the script, maybe did there is the problem?

**Comment by antipole2** [comment]
Oh dear...  a thousand apologies - my really bad.  I had omitted to commit the final version to GitHub.
Now done.  Please reload from the URL.

**Comment by antipole2** [comment]
A simple test:

1. Copy a position to the clipboard
2. Paste from clipboard.

This should paste your chosen mark style at the location you copied.

**Comment by Erickalon** [comment]
Now I got the "paste from clipboard" on both version W8 and OpenPlotter, but I got an error message when trying to paste from clipboard:
Console unparked to show message
ReferenceError: identifier 'handlClipboard' undefined

**Comment by Erickalon** [comment]
On line 120 and 146, we have the control "handlClipboard" but on other places it's "handleClipboard". Probably a script error?

**Comment by antipole2** [comment]
Yes - I have that. Am working on other issues.  Please stand by.

**Comment by antipole2** [comment]
OK - Have reworked clipboard parsing to cope with more variations.
Please re-download and try it again.

**Comment by Erickalon** [comment]
Excellent Tony! That's working fine on W8 and on OpenPlotter.
Many thanks and congratulations. I will start to play with this new tool and maybe later try to learn JavaScript for OpenCPN with your manual.
I have greatly appreciated the clarity of your instructions in this process.
Best regards,
Eric

**Comment by antipole2** [comment]
Eric... let's tidy this up.  Please confirm

1. With the correct code option, does OpenPlotter work with the plugin installed from the catalogue and has no need of the special build?
2. On Windows 8 the JavaScript statement `print("The degree symbol is º/n");`  only complies with the special build and will not compile with the version installed from the catalogue?

**Comment by Erickalon** [comment]
Hi Tony,
1. Yes, Openplotter works fine with the version 3.0.1a installed from master plugin catalogue after emptying the previous tarball in the cache.
2.  On W8 no statement appears when running  the version 3.0.1a  of JavaScript installed from the catalogue.

**Comment by antipole2** [comment]
This is not a script issue but a plugin one.
I have opened an [issue for the plugin](https://github.com/antipole2/JavaScript_pi/issues/92) and will close this one.
